server:
  host: 0.0.0.0
  port: 8080
# 系统应用配置
app:
  app_name: BMBP统一用户管理系统
  app_code: bmbp
  app_icon: 

# 数据库配置
database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: zgk0130!
  db_name: bmbp
  pool_size: 100